name: Deploy WordPress to Hostinger

on:
  push:
    branches:
      - main # Gatilho para a branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./wp-content/
          server-dir: public_html/wp-content/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/plugins/elementor/**
            **/plugins/elementor-pro/**
            **/plugins/all-in-one-wp-migration/**