name: Deploy WordPress to Hostinger

on:
  push:
    branches:
      - main # Gatilho para a branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "85.31.229.52"
          username: "u277721048.royalsistema.uios.com.br"
          password: "~7*Jq!WdXiurw9Jo"
          port: 21
          local-dir: ./wp-content/
          server-dir: public_html/wp-content/